In [1]:
import random
import nltk

In [2]:
BOT_CONFIG = {
    'intents':{
        'hello':{
            'examples':['Привет', 'Добрый день!', 'Здравствуйте', 'Хеллоу'],
            'responses':['Приветик', 'Здароу']
        },
        'goodbye':{
            'examples':['Пока', 'До свидания', 'Всего доброго', 'Гудбай'],
            'responses':['Покеда', 'Счастливо']
        },
        'thanks':{
            'examples':['Спасибо', 'Сенкс', 'Спасибо большое', 'Благодарю'],
            'responses':['Спасибки', 'thks']
        },
        'whatcanyoudo':{
            'examples':['Что ты умеешь', 'Расскажи что можешь сделать'],
            'responses':['Пиши мне', 'Просто живу']
        },
        'name':{
            'examples':['Как твое имя', 'Как тебя зовут'],
            'responses':['Бот', 'Меня зовут Бот']
        },
        'weather':{
            'examples':['Как погода?', 'Как погода в Москве?'],
            'responses':['Солнечно', 'Ясно']
        }    
},
    'failure_phrases':[
        'Я не знаю что ответить',
        'Не поняла',
        'Простите,еще раз'
         
    ]
}

In [3]:
dataset = []
for intent, intent_data in BOT_CONFIG['intents'].items():
    for example in intent_data['examples']:
        dataset.append([example, intent])
        
print(dataset)    

[['Привет', 'hello'], ['Добрый день!', 'hello'], ['Здравствуйте', 'hello'], ['Хеллоу', 'hello'], ['Пока', 'goodbye'], ['До свидания', 'goodbye'], ['Всего доброго', 'goodbye'], ['Гудбай', 'goodbye'], ['Спасибо', 'thanks'], ['Сенкс', 'thanks'], ['Спасибо большое', 'thanks'], ['Благодарю', 'thanks'], ['Что ты умеешь', 'whatcanyoudo'], ['Расскажи что можешь сделать', 'whatcanyoudo'], ['Как твое имя', 'name'], ['Как тебя зовут', 'name'], ['Как погода?', 'weather'], ['Как погода в Москве?', 'weather']]


In [4]:
X_test = [x for x, y in dataset]
y = [y for x, y in dataset]
print(X_test)
print(y)

['Привет', 'Добрый день!', 'Здравствуйте', 'Хеллоу', 'Пока', 'До свидания', 'Всего доброго', 'Гудбай', 'Спасибо', 'Сенкс', 'Спасибо большое', 'Благодарю', 'Что ты умеешь', 'Расскажи что можешь сделать', 'Как твое имя', 'Как тебя зовут', 'Как погода?', 'Как погода в Москве?']
['hello', 'hello', 'hello', 'hello', 'goodbye', 'goodbye', 'goodbye', 'goodbye', 'thanks', 'thanks', 'thanks', 'thanks', 'whatcanyoudo', 'whatcanyoudo', 'name', 'name', 'weather', 'weather']


In [5]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

In [6]:
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(X_test)
print(vectorizer.get_feature_names())
['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']
print(X.toarray())

['благодарю', 'большое', 'всего', 'гудбай', 'день', 'до', 'доброго', 'добрый', 'здравствуйте', 'зовут', 'имя', 'как', 'можешь', 'москве', 'погода', 'пока', 'привет', 'расскажи', 'свидания', 'сделать', 'сенкс', 'спасибо', 'твое', 'тебя', 'ты', 'умеешь', 'хеллоу', 'что']
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 

In [8]:
from sklearn.linear_model import LogisticRegression

In [9]:
clf = LogisticRegression(random_state=0).fit(X,y)

In [11]:
clf.classes_

array(['goodbye', 'hello', 'name', 'thanks', 'weather', 'whatcanyoudo'],
      dtype='<U12')

In [52]:
v = vectorizer.transform(['Привет :)' , 'до свидос'])
print(v.toarray())
clf.predict(X)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


array(['hello', 'hello', 'hello', 'hello', 'goodbye', 'goodbye',
       'goodbye', 'goodbye', 'thanks', 'thanks', 'thanks', 'thanks',
       'whatcanyoudo', 'whatcanyoudo', 'name', 'name', 'weather',
       'weather'], dtype='<U12')

In [21]:
clf.predict_proba(v)

array([[0.19116872, 0.43266677, 0.06438339, 0.18518959, 0.06101548,
        0.06557605],
       [0.38404382, 0.21687802, 0.06737739, 0.19924609, 0.06381442,
        0.06864026]])

In [22]:
from sklearn.svm import SVC

In [24]:
clf1 = SVC(probability=True)
clf1.fit(X,y)

SVC(probability=True)

In [25]:
v = vectorizer.transform(['Привет :)' , 'до свидос'])
print(v.toarray())
clf1.predict(v)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


array(['hello', 'goodbye'], dtype='<U12')

In [26]:
clf1.predict_proba(v)

array([[0.27594021, 0.11827874, 0.18344248, 0.22290836, 0.06500794,
        0.13442227],
       [0.10706369, 0.31093912, 0.17531867, 0.21407674, 0.06564824,
        0.12695354]])

In [27]:
from sklearn.model_selection import train_test_split

In [28]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [29]:
X_train, X_test, y_train, y_test

(<12x28 sparse matrix of type '<class 'numpy.int64'>'
 	with 23 stored elements in Compressed Sparse Row format>,
 <6x28 sparse matrix of type '<class 'numpy.int64'>'
 	with 11 stored elements in Compressed Sparse Row format>,
 ['weather',
  'hello',
  'goodbye',
  'goodbye',
  'thanks',
  'goodbye',
  'hello',
  'hello',
  'name',
  'whatcanyoudo',
  'weather',
  'goodbye'],
 ['thanks', 'hello', 'thanks', 'name', 'whatcanyoudo', 'thanks'])

In [44]:
clf1 = SVC(probability=True)
clf1.fit(X_train, y_train)

SVC(probability=True)

In [45]:
clf1.score(X_test, y_test)

0.0

In [46]:
scores = []

for _ in range(100):
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)
    clf1 = LogisticRegression()
    clf1.fit(X_train, y_train)
    score = clf1.score(X_test, y_test)
    scores.append(score)
    
    
print(sum(scores) / 100)    

0.2083333333333334


In [48]:
scores = []

for _ in range(100):
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)
    clf1 = SVC()
    clf1.fit(X_train, y_train)
    score = clf1.score(X_test, y_test)
    scores.append(score)
    
    
print(sum(scores) / 100)    

0.08166666666666669
